version: '2'
services:
    autobot-app:
        image: autobot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://autobot-postgresql:5432/autobot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=autobot-elasticsearch:9300
        ports:
            - 8080:8080
    autobot-postgresql:
        extends:
            file: postgresql.yml
            service: autobot-postgresql
    autobot-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: autobot-elasticsearch
